# Generated by Django 4.2.9 on 2024-02-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadow', '0002_first_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first',
            name='address',
        ),
    ]
