# Generated by Django 4.2.9 on 2024-02-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadow', '0004_first_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first',
            name='address',
        ),
        migrations.RemoveField(
            model_name='first',
            name='email',
        ),
        migrations.RemoveField(
            model_name='first',
            name='file',
        ),
        migrations.RemoveField(
            model_name='first',
            name='img',
        ),
    ]
