# Generated by Django 4.2.10 on 2024-03-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadow', '0006_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='second',
            name='address',
        ),
    ]
