# Generated by Django 4.2.9 on 2024-02-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('uesr_id', models.IntegerField()),
                ('user_notes', models.IntegerField()),
            ],
        ),
    ]
