# Generated by Django 4.2.9 on 2024-02-26 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='uesr_id',
            new_name='user_id',
        ),
    ]
