# Generated by Django 4.2.9 on 2024-02-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_uesr_id_notes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='user_notes',
            field=models.CharField(max_length=2500),
        ),
    ]
