# Generated by Django 4.2.9 on 2024-02-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_notes_user_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user_name',
        ),
    ]
