# Generated by Django 4.2.9 on 2024-02-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_user_remove_notes_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='user_notes_title',
            field=models.CharField(default='Title', max_length=20),
        ),
    ]
