# Generated by Django 4.2.10 on 2024-03-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user',
            new_name='user_prop',
        ),
    ]
