# Generated by Django 4.2.10 on 2024-03-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_rename_user_user_profile_user_prop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_profile',
            new_name='UserProfile',
        ),
    ]
