# Generated by Django 4.2.10 on 2024-03-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_rename_user_profile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.user'),
        ),
    ]
