# Generated by Django 4.2.10 on 2024-03-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_rename_user_user_class_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_class',
            name='user_name',
            field=models.CharField(max_length=55),
        ),
    ]
